#!/usr/bin/env python3
# -*- coding: utf-8 -*-

MENU_CMD_NONE = ""
MENU_CMD_GET_TEMP = "MENU_CMD_GET_TEMP"
MENU_CMD_GET_HUMID = "MENU_CMD_GET_HUMID"
MENU_CMD_PUSH_SW = "MENU_CMD_PUSH_SW"

MENU_CMD_QUIT = "MENU_CMD_QUIT"
