#!/usr/bin/env python3
# -*- coding: utf-8 -*-

DATA_CMD_NONE = ""
DATA_CMD_SET_TEMP = "DATA_CMD_SET_TEMP"
DATA_CMD_GET_TEMP = "DATA_CMD_GET_TEMP"
DATA_CMD_SET_HUMID = "DATA_CMD_SET_HUMID"
DATA_CMD_GET_HUMID = "DATA_CMD_GET_HUMID"
DATA_CMD_SET_PICTURE = "DATA_CMD_SET_PICTURE"
DATA_CMD_SET_COLOR = "DATA_CMD_SET_COLOR"
DATA_CMD_REG_CHANGETEMP = "DATA_CMD_REG_CHANGETEMP"
DATA_CMD_REG_CHANGEHUMID = "DATA_CMD_REG_CHANGEHUMID"
DATA_CMD_QUIT = "DATA_CMD_QUIT"
