#!/usr/bin/env python3
# -*- coding: utf-8 -*-

DISPLAY_CMD_NONE = ""
DISPLAY_CMD_NOTIFY_TEMP = "DISPLAY_CMD_NOTIFY_TEMP"
DISPLAY_CMD_NOTIFY_HUMID = "DISPLAY_CMD_NOTIFY_HUMID"
DISPLAY_CMD_NOTIFY_IPADDRESS = "DISPLAY_CMD_NOTIFY_IPADDRESS"
DISPLAY_CMD_NOTIFY_CHANGEMODE = "DISPLAY_CMD_NOTIFY_CHANGEMODE"
DISPLAY_CMD_QUIT = "DISPLAY_CMD_QUIT"
